name: gps-demo
version: '0.0.1'
summary: GPS Demo Applikation
description: |
  Listen to specific COM port:-
    $ gps-demo /dev/ttyUSB3

grade: stable
confinement: devmode
base: core18

architectures:
  - build-on: amd64
    run-on: amd64

parts:
  gps-demo:
    plugin: nodejs
    nodejs-version: 14.16.0
    nodejs-package-manager: npm    
    source: .

apps:
  gps-demo:
    command: node server.js