name: gps-demo
version: '0.0.1'
summary: GPS Demo Applikation
description: |
  Listen to specific COM port:-
    $ gps-demo /dev/ttyUSB3

grade: stable
confinement: devmode
base: core20

architectures:
  - build-on: armhf
    run-on: armhf

parts:
  gps-demo:
    plugin: npm
    npm-node-version: 14.16.0
    source: .

apps:
  gps-demo:
    command: bin/gps-demo
    plugs: 
      - network
      - network-bind
      - serial-port
